### PR TITLE
Improved code to compatibilize CakePHP versions

### PR DESCRIPTION
**Pull request by jdiefenbach83**
I use this code to get compatibilized between CakePHP versions:

```
                    if (Configure::version() < '2.7') 
                    {
                        $arr = String::tokenize($full_action, '/');
                    } 
                    else 
                    {
                        $arr = CakeText::tokenize($full_action, '/');
                    }
``'

### CODE REVIEW

**Comment by jdiefenbach83** [comment]
If you can analise the code. Feel free to modify or contact me.

Thanks

**Comment by oldskool** [comment]
@jdiefenbach83 Looks good, but it seems like your editor has also converted a lot of tabs into spaces, which makes the diff somewhat hard to read. Could you fix that back to the original state? Thanks!

**Comment by jdiefenbach83** [comment]
Hello! No problem. I can fix it. But I just used netbeans on Ubuntu. 

Could you please suggest me an editor that really works to send files at github??

**Comment by oldskool** [comment]
@jdiefenbach83 Netbeans should be able to do that, but it requires some configuration of the editor.
There's a detailed explanation with screenshots here: http://stackoverflow.com/a/1949043/214577

**Comment by oldskool** [comment]
@jdiefenbach83 I fixed the code syntax in #3. It turns out that the code style is quite a mess in this Plugin, spaces and tabs are used both in the same file and one file has linebreaks in if/else statments where the other did not. It's making me dizzy, but the diff got a little bit more readable in the end. Thanks for contributing! :+1:

**Pull request merged**
